import { allow } from 'graphql-shield'
import {
  isAppOwner,
  isAppOwnerFromLink,
  isAuth,
  isNotificationOwner,
} from '../rules'

const appMutationsShield = {
  updateMyBuilder: {
    name: 'updateMyBuilder',
    slug: 'updateMyBuilder',
    desc: '',
    role: ['superAdmin', 'platformAdmin'],
    permissions: isAuth,
  },
  subscribe: {
    name: 'subscribe',
    slug: 'subscribe',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  endMyTrial: {
    name: 'endMyTrial',
    slug: 'endMyTrial',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  // editMyPlan: {
  //   name: 'editMyPlan',
  //   slug: 'editMyPlan',
  //   desc: '',
  //   role: ['all'],
  //   permissions: isAuth,
  // },
  updateDeployRequest: {
    name: 'updateDeployRequest',
    slug: 'updateDeployRequest',
    desc: '',
    role: ['superAdmin'],
    permissions: isAuth,
  },
  deleteUser: {
    name: 'deleteUser',
    slug: 'deleteUser',
    desc: '',
    role: ['superAdmin'],
    permissions: isAuth,
  },
  generateBuild: {
    name: 'generateBuild',
    slug: 'generateBuild',
    desc: '',
    role: ['superAdmin'],
    permissions: isAuth,
  },
  addApp: {
    name: 'addApp',
    slug: 'addApp',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  updateApp: {
    name: 'updateApp',
    slug: 'updateApp',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  addDeployRequest: {
    name: 'addDeployRequest',
    slug: 'addDeployRequest',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateIosProfile: {
    name: 'updateIosProfile',
    slug: 'updateIosProfile',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateAndroidProfile: {
    name: 'updateAndroidProfile',
    slug: 'updateAndroidProfile',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateAppAssets: {
    name: 'updateAppAssets',
    slug: 'updateAppAssets',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateAppDesign: {
    name: 'updateAppDesign',
    slug: 'updateAppDesign',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateAppDesignDrawer: {
    name: 'updateAppDesignDrawer',
    slug: 'updateAppDesignDrawer',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  deleteApp: {
    name: 'deleteApp',
    slug: 'deleteApp',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  addLink: {
    name: 'addLink',
    slug: 'addLink',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  updateLink: {
    name: 'updateLink',
    slug: 'updateLink',
    desc: '',
    role: ['all'],
    permissions: isAppOwnerFromLink,
  },
  deleteLink: {
    name: 'deleteLink',
    slug: 'deleteLink',
    desc: '',
    role: ['all'],
    permissions: isAppOwnerFromLink,
  },
  addNotification: {
    name: 'addNotification',
    slug: 'addNotification',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateNotificationData: {
    name: 'updateNotificationData',
    slug: 'updateNotificationData',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  updateNotification: {
    name: 'updateNotification',
    slug: 'updateNotification',
    desc: '',
    role: ['all'],
    permissions: isNotificationOwner,
  },
}

const auth = {
  signupInApp: {
    name: 'signupInApp',
    slug: 'signupInApp',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  signinInApp: {
    name: 'signinInApp',
    slug: 'signinInApp',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  signupSuperAdmin: {
    name: 'signupSuperAdmin',
    slug: 'signupSuperAdmin',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  signup: {
    name: 'signup',
    slug: 'signup',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  fastSignup: {
    name: 'fastSignup',
    slug: 'fastSignup',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  signin: {
    name: 'signin',
    slug: 'signin',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  requestReset: {
    name: 'requestReset',
    slug: 'requestReset',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  validateCode: {
    name: 'validateCode',
    slug: 'validateCode',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  resetPassword: {
    name: 'resetPassword',
    slug: 'resetPassword',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  signOut: {
    name: 'signOut',
    slug: 'signOut',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  updateMyProfile: {
    name: 'updateMyProfile',
    slug: 'updateMyProfile',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  addNotificationToken: {
    name: 'addNotificationToken',
    slug: 'addNotificationToken',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
}
export const mutationsShield = {
  ...auth,

  ...appMutationsShield,
}
