import { allow } from 'graphql-shield'
import { isAppOwner, isAuth } from '../rules'

export const queriesShield = {
  myMailLists: {
    name: 'myMailLists',
    slug: 'myMailLists',
    desc: '',
    role: ['superAdmin'],
    permissions: isAuth,
  },
  myBuilder: {
    name: 'myBuilder',
    slug: 'myBuilder',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  me: {
    name: 'me',
    slug: 'me',
    desc: '',
    role: ['all'],
    permissions: allow,
  },
  app: {
    name: 'app',
    slug: 'app',
    desc: '',
    role: ['all'],
    // permissions: isAppOwner,
    permissions: allow,
  },
  iosProfile: {
    name: 'iosProfile',
    slug: 'iosProfile',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  androidProfile: {
    name: 'androidProfile',
    slug: 'androidProfile',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  notificationData: {
    name: 'notificationData',
    slug: 'notificationData',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  appUsers: {
    name: 'appUsers',
    slug: 'appUsers',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
  apps: {
    name: 'apps',
    slug: 'apps',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  deployRequests: {
    name: 'deployRequests',
    slug: 'deployRequests',
    desc: '',
    role: ['all'],
    permissions: isAuth,
  },
  links: {
    name: 'links',
    slug: 'links',
    desc: '',
    role: ['all'],
    // permissions: isAuth,
    permissions: allow,
  },
  notifications: {
    name: 'notifications',
    slug: 'notifications',
    desc: '',
    role: ['all'],
    permissions: isAppOwner,
  },
}
